set -g status-style bg=default #colour233
set -g status-fg white
set -g mode-style fg=black,bg=magenta
set-option -g status-position top

set -g status-left "#[fg=green]#S #[default]"
set -g status-right "#{prefix_highlight} #[fg=magenta]^_^ %Y-%m-%d %a %H:%M#[default]"
