set -g @plugin "dracula/tmux"

# left icon
set -g @dracula-show-left-icon "#S"
# weather
set -g @dracula-show-fahrenheit false
set -g @dracula-show-location false

set -g @dracula-time-format "%F %R"

set -g @dracula-plugins "ssh-session battery network weather time"
