#!/bin/sh

# a collection of install scripts to download utils for the software I use

: "${XDG_CONFIG_HOME:=$HOME/.config}"

# ==== ZSH ====
export ZSH="$HOME/.config/oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended # oh-my-zsh
rm "$HOME/.zshrc" # remove autogenerated omz .zshrc template
git clone https://github.com/zsh-users/zsh-autosuggestions.git "$ZSH_CUSTOM/plugins/zsh-autosuggestions" # zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" # zsh-syntax-highlightning

# dracula theme for zsh
OMZ_THEME_DIR="$ZSH/themes"
wget https://github.com/dracula/zsh/archive/master.zip
unzip -j master.zip "zsh-master/dracula.zsh-theme" "zsh-master/lib/*"
mkdir "$OMZ_THEME_DIR/lib"
mv dracula.zsh-theme "$OMZ_THEME_DIR"
mv async.zsh "$OMZ_THEME_DIR/lib"
rm master.zip

# ==== TMUX ====
git clone https://github.com/tmux-plugins/tpm "$XDG_CONFIG_HOME/tmux/plugins/tpm"

# ==== SPICETIFY ====
curl -fsSL https://raw.githubusercontent.com/spicetify/marketplace/main/resources/install.sh | sh

# dracula theme for spicetify
SPICETIFY_THEME_DIR=$XDG_CONFIG_HOME/spicetify/Themes
DRACULA_THEME_DIR=$SPICETIFY_THEME_DIR/Dracula
wget https://github.com/dracula/spicetify/archive/refs/heads/master.zip
mkdir "$DRACULA_THEME_DIR"
unzip -qj master.zip "spicetify-main/Dracula/*" -d "$DRACULA_THEME_DIR"
rm master.zip
# to apply
# spicetify config current_theme Dracula
#
echo "It's recommended to run \"exec zsh\" right now."
