#!/bin/sh

# a collection of install scripts to download utils for the software I use

: "${XDG_CONFIG_HOME:=$HOME/.config}"

# ==== ZSH ====
: "${ZSH:=$XDG_CONFIG_HOME/oh-my-zsh}"
: "${ZSH_CUSTOM:=$ZSH/custom}"

if ! [ -d "$ZSH" ]; then
    echo "Installing oh-my-zsh to $ZSH."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended # oh-my-zsh
    rm "$HOME/.zshrc" # remove autogenerated omz .zshrc template, will get replaced by a symlink
else
    echo "oh-my-zsh is already installed at $ZSH."
fi

export ZSH_AUTOSUG="$ZSH_CUSTOM/plugins/zsh-autosuggestions"
if [ ! -d "$ZSH_AUTOSUG" ]; then
    echo "Installing zsh-autosuggestions to $ZSH_AUTOSUG."
    git clone https://github.com/zsh-users/zsh-autosuggestions.git "$ZSH_AUTOSUG" # zsh-autosuggestions
else
    echo "zsh-autosuggestions plugin is already installed at $ZSH_AUTOSUG."
fi

export ZSH_SYNTHIGH="$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
if [ ! -d "$ZSH_SYNTHIGH" ]; then
    echo "Installing zsh-syntax-highlighting to $ZSH_SYNTHIGH."
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_SYNTHIGH" # zsh-syntax-highlighting
else
    echo "zsh-syntax-highlighting plugin is already installed at $ZSH_AUTOSUG."
fi

# dracula theme for zsh
OMZ_THEME_DIR="$ZSH/themes"

if [ ! -f "$OMZ_THEME_DIR/dracula.zsh-theme" ] || [ ! -f "$OMZ_THEME_DIR/lib/async.zsh" ]; then
    echo "Downloading dracula zsh theme to $OMZ_THEME_DIR."
    wget -qO omz-dracula.zip https://github.com/dracula/zsh/archive/master.zip
    unzip -qj omz-dracula.zip "zsh-master/dracula.zsh-theme" "zsh-master/lib/*"
    mkdir "$OMZ_THEME_DIR/lib"
    mv dracula.zsh-theme "$OMZ_THEME_DIR"
    mv async.zsh "$OMZ_THEME_DIR/lib"
    rm omz-dracula.zip
fi

# ==== TMUX ====
if [ ! -d "$XDG_CONFIG_HOME/tmux/plugins/tpm" ]; then
    echo "Installing tpm (tmux plugin manager)."
    git clone https://github.com/tmux-plugins/tpm "$XDG_CONFIG_HOME/tmux/plugins/tpm"
else
    echo "tpm (tmux plugin manager) is already installed."
fi

# ==== SPICETIFY ====
echo "Installing spicetify."
curl -fsSL https://raw.githubusercontent.com/spicetify/marketplace/main/resources/install.sh | sh

# dracula theme for spicetify
SPICETIFY_THEME_DIR=$XDG_CONFIG_HOME/spicetify/Themes
DRACULA_THEME_DIR=$SPICETIFY_THEME_DIR/Dracula
if [ ! -d "DRACULA_THEME_DIR" ]; then
    echo "Downloading dracula spicetify theme to $DRACULA_THEME_DIR."
    wget -qO spicetify-dracula.zip https://github.com/dracula/spicetify/archive/refs/heads/master.zip
    mkdir "$DRACULA_THEME_DIR"
    unzip -qj spicetify-dracula.zip "spicetify-main/Dracula/*" -d "$DRACULA_THEME_DIR"
    rm spicetify-dracula.zip
else
    echo "Dracula theme is already installed at $DRACULA_THEME_DIR."
fi

echo "Run \"chsh -s \$(which zsh)\" to change default shell to zsh."
echo "Run \"exec zsh\" to source zsh config."
